# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    api.pp.client: 'AfmRbDua1gAU-0Pa2l2uVHgb0lgrvHvco0HqhZvZsvTqpUwCGrKsEAwsnRZmN4sAZRObmIQKIdS5Ab8e'
    api.pp.secret: 'EJYJ3CA7gi-1u4tiONsUs3nW3ukwPIB5GEQ2SiaXjKA2_9aPHosov8yLEoaFn6453XDp8ZV_Fjw_cwF7'
    api.pp.uri: 'https://api.paypal.com'
    api.six.key: 'QVBJXzI0Nzk2NF83NzYwMjk2MTpac3B0ODhnU1R4dHFLcGZK'
    api.six.user: 'API_247964_08724734'
    api.six.uri: 'https://test.saferpay.com/api'
    api.six.customer: '247964'
    api.six.terminal: '17966309'
    api.geo.uri: 'http://ip-api.com/json'
    storage.img: '/var/www/html/storage/img'
    storage.pdf: '/var/www/html/storage/pdf'
    app.supported_locales: ['fr', 'de', 'en']
    api.city.name: parentsolo
    api.city.key: so03232fa975a927abf4d5e48b2e17968981c1c221
    de.trans.file: '%kernel.project_dir%/translations/messages.de.yaml'
    fr.trans.file: '%kernel.project_dir%/translations/messages.fr.yaml'
    en.trans.file: "%kernel.project_dir%/translations/messages.en.yaml"
    env(MERCURE_PUBLISH_URL): ""
    env(MERCURE_JWT_SECRET): ""
    app.url: 'https://parentsolo.disons-demain.be'
    node.token: '%env(NODE_TOKEN)%'
    postfinance.tokenisation: "https://postfinance.test.v-psp.com/Tokenization/HostedPage"
    postfinance.directlink: "https://e-payment.postfinance.ch/ncol/test/orderdirect.asp"
    pspid: "parentsoloTEST"
    userid: "parentsoloDamien"
    pswd: "Valentina0802**"
    sha: "Parentsoloch@123"
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments', '@Symfony\Component\Mercure\Publisher']

    App\Mailer\Mailing:
        arguments: ['@doctrine.orm.entity_manager', '@swiftmailer.mailer.default','@twig', '@translator']
        public: true

    App\EventListener\ExceptionListener:
        tags :
            - { name: kernel.event_listener, event: kernel.exception }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    backndev\sixpayment\Command\:
        resource: '../vendor/backndev/sixpayment/Command'
        public: true

    backndev\paypal\Subscription\:
        resource: '../vendor/backndev/paypal/Subscription'
        arguments: ['@security.context_listener']
        public: true

    App\Service\:
        resource: '../src/Service'
        arguments: ['@doctrine.orm.entity_manager', '@swiftmailer.mailer.default', '@twig']

    App\EventListener\LocaleSubscriber:
        arguments: ['@doctrine.orm.entity_manager','%kernel.default_locale%']
        # uncomment the next line if you are not using autoconfigure
        tags: [kernel.event_subscriber]
